### ISSUE TITLE
Move NeXML website to Naturalis

### ISSUE THREAD

**Issue by rvosa** [nexml/nexml#13] opened 2014-02-07 09:08 UTC
NESCent, having kindly hosted the NeXML website for many (!) years will not be able to continue this for much longer. Once Naturalis has its infra for cloud instances in place, that would be the obvious new host for NeXML.

**Comment by yeban** [comment] 2014-09-20 19:58
Duplicate of: https://github.com/nexml/nexml.github.io/issues/1

**Closed as completed by yeban** 2014-09-20 19:58 UTC
Labels: maintenance
